import 'package:rent_car_concept/models/car.dart';

List<Car> cars = [
  Car(
    brand: 'Toyota',
    imagePath: 'assets/camry.png',
    model: 'Camry',
    location: 'New York',
    fuelType: 'Petrol',
    transmissionType: 'Automatic',
    distance: 15000,
    fuelCapacity: 55.0,
    pricePerHour: 20.0,
    rentalPrice: 100.0,
    rating: 4.5,
    //mileage: true,
    isAvailable: true, id: '1',
  ),
  Car(
    id: '2',
    brand: 'Honda',
    imagePath: 'assets/civic.png',
    model: 'Civic',
    location: 'Los Angeles',
    fuelType: 'Petrol',
    transmissionType: 'Automatic',
    distance: 12000,
    fuelCapacity: 50.0,
    pricePerHour: 18.0,
    rentalPrice: 90.0,
    rating: 4.7,
    //mileage: true,
    isAvailable: true,
  ),
  Car(
    id: '3',
    imagePath: 'assets/ford.png',
    brand: 'Ford',
    model: 'Mustang',
    location: 'Miami',
    fuelType: 'Petrol',
    transmissionType: 'Manual',
    distance: 20000,
    fuelCapacity: 60.0,
    pricePerHour: 30.0,
    rentalPrice: 150.0,
    rating: 4.8,
    //  mileage: false,
    isAvailable: true,
  ),
  Car(
    id: '4',
    imagePath: 'assets/tahoe.png',
    brand: 'Chevrolet',
    model: 'Tahoe',
    location: 'Chicago',
    fuelType: 'Diesel',
    transmissionType: 'Automatic',
    distance: 18000,
    fuelCapacity: 70.0,
    pricePerHour: 25.0,
    rentalPrice: 130.0,
    rating: 4.6,
    //mileage: true,
    isAvailable: true,
  ),
  Car(
    id: '5',
    imagePath: 'assets/bmw_3series.png',
    brand: 'BMW',
    model: '3 Series',
    location: 'San Francisco',
    fuelType: 'Petrol',
    transmissionType: 'Automatic',
    distance: 14000,
    fuelCapacity: 55.0,
    pricePerHour: 35.0,
    rentalPrice: 170.0,
    rating: 4.9,
    // mileage: false,
    isAvailable: true,
  ),
  Car(
    id: '6',
    imagePath: 'assets/mercedes+benz+eclass.png',
    brand: 'Mercedes-Benz',
    model: 'E-Class',
    location: 'Houston',
    fuelType: 'Diesel',
    transmissionType: 'Automatic',
    distance: 16000,
    fuelCapacity: 65.0,
    pricePerHour: 40.0,
    rentalPrice: 200.0,
    rating: 4.8,
    // mileage: true,
    isAvailable: false,
  ),
  Car(
    id: '7',
    imagePath: 'assets/audi_q7.png',
    brand: 'Audi',
    model: 'Q7',
    location: 'Phoenix',
    fuelType: 'Petrol',
    transmissionType: 'Automatic',
    distance: 17000.0,
    fuelCapacity: 75.0,
    pricePerHour: 38.0,
    rentalPrice: 190.0,
    rating: 4.7,
    //mileage: false,
    isAvailable: true,
  ),
  Car(
    id: '8',
    imagePath: 'assets/tesla_model3.png',
    brand: 'Tesla',
    model: 'Model 3',
    location: 'Las Vegas',
    fuelType: 'Electric',
    transmissionType: 'Automatic',
    distance: 10000.0,
    fuelCapacity: 0.0,
    pricePerHour: 45.0,
    rentalPrice: 220.0,
    rating: 4.9,
    // mileage: true,
    isAvailable: false,
  ),
  Car(
    id: '10',
    imagePath: 'assets/hyundai_santafe.png',
    brand: 'Hyundai',
    model: 'Santa Fe',
    location: 'Dallas',
    fuelType: 'Petrol',
    transmissionType: 'Automatic',
    distance: 14000.0,
    fuelCapacity: 55.0,
    pricePerHour: 24.0,
    rentalPrice: 120.0,
    rating: 4.6,
    // mileage: true,
    isAvailable: false,
  ),
];
